# Generated by Django 5.1.3 on 2024-11-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usersubmission_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubmission',
            name='pdf_file',
            field=models.BinaryField(),
        ),
    ]
